In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/ml-fall2019-android-malware/readme.pdf
/kaggle/input/ml-fall2019-android-malware/data/data/sample-solutions/sample.solution.all.positive.csv
/kaggle/input/ml-fall2019-android-malware/data/data/sample-solutions/sample.solution.half-neg.csv
/kaggle/input/ml-fall2019-android-malware/data/data/data-splits/data.train
/kaggle/input/ml-fall2019-android-malware/data/data/data-splits/eval.id
/kaggle/input/ml-fall2019-android-malware/data/data/data-splits/data.eval.anon
/kaggle/input/ml-fall2019-android-malware/data/data/data-splits/data.test


In [2]:
from scipy.sparse import csr_matrix
import numpy as np

In [3]:

def read_libsvm(fname, num_features=0):
    '''
        Reads a libsvm formatted data and outputs the training set (sparse matrix)[1], 
        the label set and the number of features. The number of features
        can either be provided as a parameter or inferred from the data.

		Example usage:
		
		X_train, y_train, num_features = read_libsvm('data_train')
		X_test, y_test, _ = read_libsvm('data_test', num_features)

		[1] https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html
	'''
    data = []
    y = []
    row_ind = []
    col_ind = []
    with open(fname) as f:
        lines = f.readlines()
        for i, line in enumerate(lines):
            elements = line.split()
            y.append(int(elements[0]))
            for el in elements[1:]:
                row_ind.append(i)
                c, v = el.split(":")
                col_ind.append(int(c))
                data.append(float(v))
    if num_features == 0:
        num_features = max(col_ind) + 1
    X = csr_matrix((data, (row_ind, col_ind)), shape=(len(y), num_features+1))

    return X, np.array(y), num_features

In [4]:
X_train, y_train, num_features = read_libsvm('/kaggle/input/ml-fall2019-android-malware/data/data/data-splits/data.train',360)
X_test, y_test, _ = read_libsvm('/kaggle/input/ml-fall2019-android-malware/data/data/data-splits/data.test', 360)


In [5]:
#for ele in y_train:
 #   if ele = 0:
  #      y_train 
len_arr = len(y_train)

for i in range(0,len_arr):
    if y_train[i]==0:
        y_train[i]=-1
        
y_train        

array([ 1, -1, -1, ..., -1, -1, -1])

In [6]:
X_test_df = pd.DataFrame(X_test.toarray())
#X_test_df
y_test

array([1, 0, 0, ..., 0, 0, 1])

In [7]:
len_arr2 = len(y_test)

for i in range(0,len_arr2):
    if y_test[i]==0:
        y_test[i]=-1
        
y_test 

array([ 1, -1, -1, ..., -1, -1,  1])

In [8]:
df = pd.DataFrame(X_train.toarray())
#n_array =np.array(df)
df

0    1       2    3    4    5    6    7    8     9    ...  351  352  \
0     0.0  0.0   360.0  0.0  0.0  0.0  0.0  0.0  0.0  20.0  ...  0.0  0.0   
1     0.0  0.0   279.0  0.0  0.0  0.0  0.0  0.0  0.0   2.0  ...  0.0  0.0   
2     0.0  0.0   216.0  0.0  0.0  0.0  0.0  0.0  0.0  11.0  ...  0.0  0.0   
3     0.0  0.0    25.0  0.0  0.0  0.0  0.0  0.0  0.0  17.0  ...  0.0  0.0   
4     0.0  0.0   136.0  0.0  0.0  0.0  0.0  0.0  0.0  13.0  ...  0.0  0.0   
...   ...  ...     ...  ...  ...  ...  ...  ...  ...   ...  ...  ...  ...   
7592  0.0  0.0    10.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0  ...  0.0  0.0   
7593  0.0  0.0   192.0  0.0  0.0  0.0  0.0  0.0  0.0   6.0  ...  0.0  0.0   
7594  0.0  0.0   157.0  0.0  0.0  0.0  0.0  0.0  0.0   1.0  ...  0.0  0.0   
7595  0.0  0.0   546.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0  ...  0.0  0.0   
7596  0.0  0.0  1280.0  0.0  0.0  0.0  0.0  0.0  0.0  19.0  ...  0.0  0.0   

      353  354  355  356  357  358     359     360  
0     0.0  0.0  0.0  0.0  0.0  0.0  3379.0   342.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  3247.0   400.0  
2     0.0  0.0  0.0  1.0  0.0  0.0  3133.0   528.0  
3     0.0  0.0  0.0  0.0  0.0  0.0   748.0  5211.0  
4     0.0  0.0  0.0  0.0  0.0  0.0   858.0   239.0  
...   ...  ...  ...  ...  ...  ...     ...     ...  
7592  0.0  0.0  0.0  0.0  0.0  0.0     3.0    22.0  
7593  0.0  0.0  0.0  1.0  0.0  0.0  1468.0    77.0  
7594  0.0  0.0  0.0  0.0  0.0  0.0   853.0   254.0  
7595  0.0  0.0  0.0  0.0  0.0  0.0     4.0   264.0  
7596  0.0  0.0  0.0  0.0  0.0  0.0  4149.0   337.0  

[7597 rows x 361 columns]

In [9]:
def predict(row, w , b ):
    mul=(np.dot(np.array(row),w)+b)
    result = -1
    if mul>=0:
        result = 1
    return result

def update(row_df, y, w, b, lr):
    w_new=[]
    b_new = 0
    for i, ele in enumerate(row_df):
        w_new.append(w[i]+lr*y*ele)
        b_new = b + lr*y
    w_new = np.array(w_new)   
    return w_new , b_new    

def perceptron(X_df, y_t , epochs=20, lr=0.01):
    rgen = np.random.RandomState(0)
    b = rgen.uniform(-0.01,0.01,1) #initialize bias
    w = rgen.normal(loc=0.0, scale=0.01, size=361)
    arr_acc=[]
    error=[]
    #op_predict =[]
    for e in range(epochs):
        errors=0
        #print("Epoch : {}".format(e))
        for index, row in X_df.iterrows():
            y_dash=predict(row ,w ,b)
            #op_predict.append(y_dash)
            if(y_t[index]!=y_dash):
                w, b = update(row, y_t[index], w, b, lr)
                errors=errors+1
        error.append(errors)
        #print("Accuracy in epoch : {} ".format((len(y_t)-errors)/len(y_t)))
        arr_acc.append((len(y_t)-errors)/len(y_t))
    accuracy = (len(y_t)-errors)/len(y_t)  
    return w,b,error, accuracy, arr_acc   

In [10]:
w,b, error,accuracy,_ = perceptron(df, y_train, 20, 0.01)


In [11]:
error

[2752,
 2612,
 2612,
 2592,
 2619,
 2554,
 2559,
 2617,
 2526,
 2569,
 2477,
 2569,
 2497,
 2545,
 2566,
 2500,
 2475,
 2464,
 2517,
 2470]

In [12]:
accuracy

0.6748716598657365

In [13]:
w_test,b_test,_,test_accuracy,_ = perceptron(X_test_df, y_test,20,0.01)

In [14]:
print(w_test,b_test,test_accuracy)

[ 7.41591741e-03 -5.92444709e+01  1.50038732e+03  1.33354538e-02
 -8.42724054e-03  1.96992445e-02  1.26611853e-02 -5.05876540e-03
  2.54520078e-02  1.12005081e+03  4.84312154e-03  8.28257914e+01
 -1.81582573e-03  1.41020463e-02  4.49762553e+01 -1.60007248e+02
 -9.60754612e-03  3.76926975e-03  3.34389285e-04  6.80567244e-03
 -1.56349669e-02 -1.61884567e+03 -2.42149514e-03  1.51439128e-02
 -1.05533306e+01  2.48657047e+03  6.30994627e+02  1.53502913e-02
  5.66440038e-03  1.49265092e-03  2.18739217e+02  1.21333955e+02
  1.78748405e-02 -5.80569517e+00  1.75386533e-03 -1.36790463e+03
 -1.08580060e-02  1.14909464e+04 -3.85863336e-03 -7.75762353e-03
  9.83799571e+01 -1.07649332e+02  5.00024853e+01 -3.12453354e-04
 -1.39473962e-03 -1.90655979e-03  4.48637527e-03 -9.92429772e-03
 -2.25939656e-03 -1.65457077e-02  6.99360277e+00 -4.79419801e-03
  3.11363503e-03  1.35421224e+03 -3.07364810e-03 -3.66523941e-03
  1.31904120e+03 -1.62102458e+03  4.25393398e-03 -2.79711835e-04
  1.47598983e-02  3.87646

In [15]:
y_test

array([ 1, -1, -1, ..., -1, -1,  1])

In [16]:
X_eval, y_eval, _ = read_libsvm('/kaggle/input/ml-fall2019-android-malware/data/data/data-splits/data.test', 360)


In [17]:
_,_,_,test_accuracy,_ = perceptron(X_test_df, y_test,20,0.01)

In [18]:
X_eval_df = pd.DataFrame(X_eval.toarray())
#n_array =np.array(df)
X_eval_df

0    1      2    3    4    5    6    7    8      9    ...  351  352  \
0     0.0  0.0   45.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0  ...  0.0  0.0   
1     0.0  0.0  448.0  0.0  0.0  0.0  0.0  0.0  0.0   17.0  ...  0.0  0.0   
2     0.0  0.0  165.0  0.0  0.0  0.0  0.0  0.0  0.0    5.0  ...  0.0  0.0   
3     0.0  0.0   69.0  0.0  0.0  0.0  0.0  0.0  0.0    1.0  ...  0.0  0.0   
4     0.0  0.0    9.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0  ...  0.0  0.0   
...   ...  ...    ...  ...  ...  ...  ...  ...  ...    ...  ...  ...  ...   
2526  0.0  0.0   22.0  0.0  0.0  0.0  0.0  0.0  0.0    1.0  ...  0.0  0.0   
2527  0.0  0.0    2.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0  ...  0.0  0.0   
2528  0.0  0.0  611.0  0.0  0.0  0.0  0.0  0.0  0.0   52.0  ...  0.0  0.0   
2529  0.0  0.0  394.0  0.0  0.0  0.0  0.0  0.0  0.0  183.0  ...  0.0  0.0   
2530  0.0  0.0  278.0  0.0  0.0  0.0  0.0  0.0  0.0   34.0  ...  0.0  0.0   

      353  354  355  356  357  358      359    360  
0     0.0  0.0  0.0  0.0  0.0  0.0     49.0   19.0  
1     0.0  0.0  0.0  1.0  0.0  0.0   5289.0  419.0  
2     0.0  0.0  0.0  1.0  0.0  0.0  10895.0  685.0  
3     0.0  0.0  0.0  0.0  0.0  0.0   6351.0  356.0  
4     0.0  0.0  0.0  0.0  0.0  0.0    559.0  382.0  
...   ...  ...  ...  ...  ...  ...      ...    ...  
2526  0.0  0.0  0.0  0.0  0.0  0.0   2551.0  217.0  
2527  0.0  0.0  0.0  0.0  0.0  0.0    310.0   80.0  
2528  0.0  0.0  0.0  1.0  0.0  0.0   7134.0  776.0  
2529  0.0  0.0  0.0  1.0  0.0  0.0   6127.0  839.0  
2530  0.0  0.0  0.0  0.0  0.0  0.0   4577.0  634.0  

[2531 rows x 361 columns]

In [19]:
op_predict=[]
for index, row in X_eval_df.iterrows():
        y_dash=predict(row ,w_test ,b_test)
        op_predict.append(y_dash)
        

In [20]:
len_arr3 = len(op_predict)
#print(op_predict)
for i in range(0,len_arr3):
    if op_predict[i]==-1:
        op_predict[i]=0
op_predict

[0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,


In [21]:
eval_id_list=[]
with open("/kaggle/input/ml-fall2019-android-malware/data/data/data-splits/eval.id") as f:
    lines = f.readlines()
    
    
for ele in lines:
    ele=ele.rstrip("\n")
    print(ele)
    eval_id_list.append(ele)


2591
10174
4764
5429
11235
4120
4549
4752
12562
3783
8804
12427
4702
10942
9152
9638
6396
7296
10093
12304
7567
6473
1509
11626
1356
10024
46
8951
10057
1937
1554
1326
11494
2165
4462
3764
11997
10696
7776
3004
12470
11927
1949
3053
1309
2114
8314
1282
9413
9008
3079
8487
1614
6642
8229
12381
1559
5626
10724
4919
9996
7289
2177
1732
4190
3466
6940
1906
4312
2118
1987
8611
8586
1307
6305
5452
2468
2277
10046
1756
2499
4303
2436
10912
5830
8904
5189
5158
4684
2401
6295
12543
7902
3691
1258
11151
10565
7436
6687
3463
4765
12597
3282
5986
8286
994
587
7131
105
1984
10414
8004
8141
3057
8348
7954
3828
12168
2491
5578
8231
8827
1864
10631
9901
8096
3152
10387
1865
750
8134
6933
8964
1280
6592
3808
7812
4356
5836
241
1268
9877
4899
4158
4176
6267
4722
9267
7489
2770
7801
9853
2827
9016
8766
12165
6164
4056
331
11386
8837
5972
11932
1385
9556
599
10749
3172
5363
3270
457
5881
2087
1303
7635
12237
1244
5312
4217
1206
3743
3023
11129
11902
5347
10423
10937
4403
5193
3433
5675
10104
8761
6007
566

In [22]:
eval_id_list


['2591',
 '10174',
 '4764',
 '5429',
 '11235',
 '4120',
 '4549',
 '4752',
 '12562',
 '3783',
 '8804',
 '12427',
 '4702',
 '10942',
 '9152',
 '9638',
 '6396',
 '7296',
 '10093',
 '12304',
 '7567',
 '6473',
 '1509',
 '11626',
 '1356',
 '10024',
 '46',
 '8951',
 '10057',
 '1937',
 '1554',
 '1326',
 '11494',
 '2165',
 '4462',
 '3764',
 '11997',
 '10696',
 '7776',
 '3004',
 '12470',
 '11927',
 '1949',
 '3053',
 '1309',
 '2114',
 '8314',
 '1282',
 '9413',
 '9008',
 '3079',
 '8487',
 '1614',
 '6642',
 '8229',
 '12381',
 '1559',
 '5626',
 '10724',
 '4919',
 '9996',
 '7289',
 '2177',
 '1732',
 '4190',
 '3466',
 '6940',
 '1906',
 '4312',
 '2118',
 '1987',
 '8611',
 '8586',
 '1307',
 '6305',
 '5452',
 '2468',
 '2277',
 '10046',
 '1756',
 '2499',
 '4303',
 '2436',
 '10912',
 '5830',
 '8904',
 '5189',
 '5158',
 '4684',
 '2401',
 '6295',
 '12543',
 '7902',
 '3691',
 '1258',
 '11151',
 '10565',
 '7436',
 '6687',
 '3463',
 '4765',
 '12597',
 '3282',
 '5986',
 '8286',
 '994',
 '587',
 '7131',
 '105',
 

In [23]:
0.6693006716712762 epochs=10, lr =0.01
0.6760173844330304 epochs=20, lr = 0.01














SyntaxError: invalid syntax (<ipython-input-23-72181145e857>, line 1)

In [24]:
list_of_tuples = list(zip(eval_id_list, op_predict))  
    
# Assign data to tuples.  
list_of_tuples   
  
  
# Converting lists of tuples into  
# pandas Dataframe.  
df_new = pd.DataFrame(list_of_tuples, columns = ['example_id', 'label'])  
     
# Print data.  
df_new


example_id  label
0          2591      0
1         10174      0
2          4764      0
3          5429      0
4         11235      0
...         ...    ...
2526       1007      0
2527       1681      1
2528       9320      0
2529       2301      0
2530       1175      0

[2531 rows x 2 columns]

In [25]:
df_new.to_csv(r'df_new.csv')



In [26]:
from IPython.display import FileLink
FileLink(r'df_new.csv')

/kaggle/working/df_new.csv

In [27]:
len_arr3 = len(op_predict)

for i in range(0,len_arr3):
    if op_predict[i]==0:
        op_predict[i]=1
    if op_predict[i]==1:
        op_predict[i]=0
op_predict

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [28]:
df

0    1       2    3    4    5    6    7    8     9    ...  351  352  \
0     0.0  0.0   360.0  0.0  0.0  0.0  0.0  0.0  0.0  20.0  ...  0.0  0.0   
1     0.0  0.0   279.0  0.0  0.0  0.0  0.0  0.0  0.0   2.0  ...  0.0  0.0   
2     0.0  0.0   216.0  0.0  0.0  0.0  0.0  0.0  0.0  11.0  ...  0.0  0.0   
3     0.0  0.0    25.0  0.0  0.0  0.0  0.0  0.0  0.0  17.0  ...  0.0  0.0   
4     0.0  0.0   136.0  0.0  0.0  0.0  0.0  0.0  0.0  13.0  ...  0.0  0.0   
...   ...  ...     ...  ...  ...  ...  ...  ...  ...   ...  ...  ...  ...   
7592  0.0  0.0    10.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0  ...  0.0  0.0   
7593  0.0  0.0   192.0  0.0  0.0  0.0  0.0  0.0  0.0   6.0  ...  0.0  0.0   
7594  0.0  0.0   157.0  0.0  0.0  0.0  0.0  0.0  0.0   1.0  ...  0.0  0.0   
7595  0.0  0.0   546.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0  ...  0.0  0.0   
7596  0.0  0.0  1280.0  0.0  0.0  0.0  0.0  0.0  0.0  19.0  ...  0.0  0.0   

      353  354  355  356  357  358     359     360  
0     0.0  0.0  0.0  0.0  0.0  0.0  3379.0   342.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  3247.0   400.0  
2     0.0  0.0  0.0  1.0  0.0  0.0  3133.0   528.0  
3     0.0  0.0  0.0  0.0  0.0  0.0   748.0  5211.0  
4     0.0  0.0  0.0  0.0  0.0  0.0   858.0   239.0  
...   ...  ...  ...  ...  ...  ...     ...     ...  
7592  0.0  0.0  0.0  0.0  0.0  0.0     3.0    22.0  
7593  0.0  0.0  0.0  1.0  0.0  0.0  1468.0    77.0  
7594  0.0  0.0  0.0  0.0  0.0  0.0   853.0   254.0  
7595  0.0  0.0  0.0  0.0  0.0  0.0     4.0   264.0  
7596  0.0  0.0  0.0  0.0  0.0  0.0  4149.0   337.0  

[7597 rows x 361 columns]

In [29]:
df_new

example_id  label
0          2591      0
1         10174      0
2          4764      0
3          5429      0
4         11235      0
...         ...    ...
2526       1007      0
2527       1681      1
2528       9320      0
2529       2301      0
2530       1175      0

[2531 rows x 2 columns]

In [30]:
import sklearn.metrics as metrics
precision=metrics.precision_score(y_test, y_predict)
recall=metrics.recall_score(y_test, y_predict)
print("Accuracy:",metrics.accuracy_score(y_test, y_predict))
print("Precision:",metrics.precision_score(y_test, y_predict))
print("Recall:",metrics.recall_score(y_test, y_predict))

NameError: name 'y_predict' is not defined

In [31]:
###########test set fscore:
op_predict_2=[]
for index, row in X_test_df.iterrows():
        y_dash=predict(row ,w_test ,b_test)
        op_predict_2.append(y_dash)

In [32]:
import sklearn.metrics as metrics
precision=metrics.precision_score(y_test, op_predict_2)
recall=metrics.recall_score(y_test, op_predict_2)
print("Accuracy:",metrics.accuracy_score(y_test, op_predict_2))
print("Precision:",metrics.precision_score(y_test, op_predict_2))
print("Recall:",metrics.recall_score(y_test, op_predict_2))

Accuracy: 0.7305412880284472
Precision: 0.5958378970427163
Recall: 0.6347724620770129


In [33]:
F1 = 2 * (precision * recall) / (precision + recall)
F1

0.6146892655367232